// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1beta1 "github.com/upbound/provider-azuread/v2/apis/namespaced/applications/v1beta1"
	v1beta1groups "github.com/upbound/provider-azuread/v2/apis/namespaced/groups/v1beta1"
	v1beta1serviceprincipals "github.com/upbound/provider-azuread/v2/apis/namespaced/serviceprincipals/v1beta1"
	v1beta1users "github.com/upbound/provider-azuread/v2/apis/namespaced/users/v1beta1"
	v1alpha1 "github.com/upbound/provider-azuread/v2/apis/namespaced/v1alpha1"
	v1beta1namespaced "github.com/upbound/provider-azuread/v2/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1beta1.SchemeBuilder.AddToScheme,
		v1beta1groups.SchemeBuilder.AddToScheme,
		v1beta1serviceprincipals.SchemeBuilder.AddToScheme,
		v1beta1users.SchemeBuilder.AddToScheme,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1beta1namespaced.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
