name: Publish Provider Package to Harbor

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version string to use while publishing the package (e.g. v1.0.0-alpha.1)"
        default: ''
        required: false
      go-version:
        description: 'Go version to use if building needs to be done'
        default: '1.25.11'
        required: false

jobs:
  publish-provider-package:
    runs-on: [self-hosted, linux, x64, krubecible, holybits-shared]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ github.event.inputs.go-version }}
      
      - name: Build provider binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o _output/bin/linux_amd64/provider ./cmd/provider/
      
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.dittmanfamily.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cluster/images/provider-azuread/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            harbor.dittmanfamily.com/holybitsllc/provider-azuread:${{ github.event.inputs.version }}
            harbor.dittmanfamily.com/holybitsllc/provider-azuread:latest
